# Generated by Django 5.2.1 on 2025-05-10 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critica', '0001_initial'),
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='id_libros',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criticas', to='libros.libro'),
        ),
    ]
