# Generated by Django 5.2.1 on 2025-05-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critica', '0002_alter_critica_id_libros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='contenido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='critica',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
