# Generated by Django 5.2.1 on 2025-05-11 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critica', '0003_alter_critica_contenido_alter_critica_updated'),
        ('libros', '0002_libro_leido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='critica',
            name='id_libros',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='criticas', to='libros.libro'),
        ),
    ]
