# Generated by Django 5.2.1 on 2025-05-12 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0002_libro_leido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='contenido',
            field=models.CharField(max_length=150),
        ),
    ]
