# Generated by Django 5.2.1 on 2025-05-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0003_alter_libro_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='contenido',
            field=models.TextField(max_length=200),
        ),
    ]
