# Generated by Django 5.2.1 on 2025-05-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0005_rename_id_libros_libro_usuario_alter_libro_contenido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libros/'),
        ),
    ]
